-- =============================================================================
-- V003 — source_state: staged-cursor watermarks for the ingestion pipeline
--
-- Ingestion is modeled as three decoupled, independently-gated stages —
-- fetch (scrape) → load (ingest raw) → build (aggregates). This table holds the
-- fetch/load cursors for each source; the build stage keeps its existing
-- per-congress vote_similarity_state watermark.
--
-- Readiness handshake: load.cursor is the fetch.cursor value the load has fully
-- consumed (read at run start, written on success). A load runs only when
-- fetch.cursor has advanced past load.cursor (or load has never run). The cron
-- time is a soft schedule; this cursor is the correctness gate. A crash mid-run
-- leaves load.cursor unadvanced, so the next run re-checks readiness and re-walks
-- idempotently.
--
-- DO NOT edit this file once it has been applied anywhere — Flyway checksums
-- applied migrations. To change the schema, add a new V0NN__*.sql migration.
-- =============================================================================

CREATE TABLE source_state (
  source_name TEXT        NOT NULL,
  stage       TEXT        NOT NULL CHECK (stage IN ('fetch', 'load')),
  cursor      TIMESTAMPTZ,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (source_name, stage)
);

COMMENT ON TABLE source_state IS E'@omit\nStaged-cursor watermarks (fetch/load) for the ingestion pipeline — internal, not exposed via GraphQL.';
